version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: git clone https://github.com/cloudfoundry/bosh-deployment
      - run: git clone https://github.com/cloudfoundry/cf-deployment
      - run: sudo chmod a+rw /var/run/docker.sock
      - run: echo "export CFDOMAIN=$(hostname -I | awk '{print $1}').xip.io" >> $BASH_ENV
      - run: sudo wget https://github.com/cloudfoundry/bosh-cli/releases/download/v5.4.0/bosh-cli-5.4.0-linux-amd64 -O /usr/bin/bosh && sudo chmod +x  /usr/bin/bosh
      - run: 
          command: ./cf-deploy.sh 
          no_output_timeout: 3600
      - run: wget "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" -O - | sudo tar xvz -C /usr/bin
      - run: ./cf-test.sh
