version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: git clone https://github.com/cloudfoundry/bosh-deployment
      - run: git clone https://github.com/cloudfoundry/cf-deployment
      - run: sudo chmod a+rw /var/run/docker.sock
      - run: export HOST_IP=$(hostname -I | awk '{print $1}')
      - run: ./cf-deploy.sh 
      - run: ./cf-test.sh